language: julia
julia:
  - 0.6
os:
  - linux
notifications:
  email: true
branches:
  only:
    - master
    - docs
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("MovingWeightedLeastSquares");'
after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("MovingWeightedLeastSquares")); include(joinpath("docs", "make.jl"))'
