site_name:        MovingWeightedLeastSquares.jl
repo_url:         https://github.com/vutunganh/MovingWeightedLeastSquares.jl
site_description: An implementation of the moving weighted least squares method
site_author:      vutunganh

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
